title: Juridisch Analyse Schema
description: Juridisch Analyse Schema
url: "https://github.com/diederikd/JAS_documentatie/"

github:
  private: false
  license:
    name: Apache-2.0
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/diederikd/JAS_documentatie/"

defaults:
  - scope:
      path: "**/*.*"
    values:
      sitemap: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
